Add update script to enforce commits from develop

diff --git a/.github/workflows/enforce_commits_from_develop.yml b/.github/workflows/enforce_commits_from_develop.yml
--- a/.github/workflows/enforce_commits_from_develop.yml
+++ b/.github/workflows/enforce_commits_from_develop.yml
@@ -5,28 +5,15 @@ name: Disallow any merging to master if this is not coming from develop
 # Controls when the action will run. Workflow runs when manually triggered using the UI
 # or API.
 on:
-  workflow_dispatch:
-    # Inputs the workflow accepts.
-    inputs:
-      name:
-        # Friendly description to be shown in the UI instead of 'name'
-        description: 'Person to greet'
-        # Default value if no value is explicitly provided
-        default: 'World'
-        # Input has to be provided for the workflow to run
-        required: true
-        # The data type of the input
-        type: string
+  pull_request:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "greet"
-  greet:
-    # The type of runner that the job will run on
+  check_branch:
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-    # Runs a single command using the runners shell
-    - name: Send greeting
-      run: echo "Hello ${{ inputs.name }}"
+      - name: Check branch
+        if: github.base_ref == 'main' && github.head_ref != 'develop' && github.head_ref.contains('hot_fix_') == false
+        run: |
+            echo "ERROR: You can only merge to main branch from develop branch or a hot_fix_ branch."
+            exit 1
